batch_size: 1
resize_x: 256
resize_y: 256
learning_rate: 0.1
train_set_split: 0.8
epoch: 2
encoder_type: "resnet34"
transforms_type: "patches"
use_patches: true
architecture: "Unet"
in_channels: 3
out_classes: 1
data_path: './data_original_size'
pipeline_name: 'patches'