batch_size: 64
resize_x: 256
resize_y: 256
learning_rate: 0.1
train_set_split: 0.8
epoch: 10
encoder_type: "resnet34"
transforms_type: "full-image-resize"
use_patches: false
architecture: "DeepLabV3"
in_channels: 3
out_classes: 1
data_path: './data_wire_clean'
pipeline_name: 'default'
load_checkpoint: false
load_model_path: 'checkpoints/cable_seg_model_20241217_104633.pth'