batch_size: 64
resize_x: 256
resize_y: 256
learning_rate: 0.1
train_set_split: 0.8
epoch: 200
encoder_type: "resnet34"
transforms_type: "full-image-resize"
use_patches: false
model_name: "Unet"
in_channels: 3
out_classes: 1
data_path: './data_original_size'
pipeline_name: 'default'