batch_size: 64
resize_x: 256
resize_y: 256
learning_rate: 0.1
train_set_split: 0.8
epoch: 100
encoder_type: "resnet34"
transforms_type: "full-image-resize"
use_patches: false
architecture: "DeepLabV3"
in_channels: 3
out_classes: 1
data_path: './data_wire_misc'
pipeline_name: 'default'
load_checkpoint: true
load_model_path: 'checkpoints/cable_seg_DeepLabV3_20241217_135354_epoch005.pth'